language: go

go:
  - "1.10.x"
  - "1.9.x"

# build runs in fast boot time container-based virtual environment
sudo: false

notifications:
  email: false

before_script:
  # Vet examines Go source code and reports suspicious constructs
  - go vet ./...

script:
  - go test -v -race ./...
